### ISSUE TITLE
ezblocker 3.0 killing spotify

### ISSUE THREAD

**Issue by ghost** [OpenByteDev/EZBlocker3#10]
EzBlocker just kills Spotify out of nowhere. An ad is not playing, I'm litterally in the middle of a song (Billie Jean) and EzBlocker just grabs Spotify by its arm and says "ight were headin out"

the og ezblocker didnt do this and that is the reason im switching back. sure the music would be sometimes muted after a reboot but i can just press win+g and unmute it

**Comment by OpenByteDev** [comment]
If you want the problem to be fixed pls help me by enabling the debug mode in the settings and sending me the log.txt that gets generated next to the EZBlocker3.exe (once the bug occurs again).

You can also have a look at my new Spotify Ad Blocker/Muter named [BurntSushi](https://github.com/OpenByteDev/BurntSushi).
