### ISSUE TITLE
Add option to start Spotify in tray (or at least minimized) whenever aggressive reopens the app.

### ISSUE THREAD

**Issue by MisterMustache** [OpenByteDev/EZBlocker3#12]
The aggressive blocking feature is fabulous and I love It, but I still have to disable It when I'm working or playing games because It reopens the Spotify app as the top window. This forces you to either minimize Spotify or click the app under It so the actually active app (game or work program) comes into focus again. 

(If there is a hidden setting or config file that enables Spotify to always start in tray please do tell because that could work aswell. Thanks)

**Comment by OpenByteDev** [comment]
I have not been able to find an easy and reliable method to restart spotify minimized or in the tray. But you can try out my other spotify ad blocker called [BurntSushi](https://github.com/OpenByteDev/BurntSushi) which does neither restart nor mute the ads but straight up removes them.

**Comment by MisterMustache** [comment]
I tried out BurntSushi and It works most of the time... But It or spotify constantly crash.

I can think of 2 solutions to the minimization problem (one more "botched" than the other):
 - You could either run Spotify with a `start` batch command and `/MIN` argument. (This could be a setting in the settings menu)
 - Or you could let the user modify some sort of config file/reg entry where you could specify which file to run when restarting Spotify. This would enable me to run a .vbs script that would have the `/min` argument already in place instead of Spotify.exe directly.

**Comment by OpenByteDev** [comment]
BurntSushi crashes when you use a Spotify version that is not up to date. (see https://github.com/OpenByteDev/BurntSushi/issues/2)

I tried you suggestions but both failed:

A shortcut with `Run` set to `Minimised`
![image](https://user-images.githubusercontent.com/22861309/118852261-e89a4780-b8d2-11eb-8ef8-3a705bc0a0b1.png)

This VBScript (works with other programs)
```vbs
set s = createobject("WScript.Shell")
s.run "Spotify.exe", 2
```

**Comment by MisterMustache** [comment]
I just tested It out myself as well and confirmed It doesn't work. When suggesting I relied on this method working. 
Too bad... It seems that such a solution is not possible at the moment.
