### ISSUE TITLE
It failed to block/mute video ads 

### ISSUE THREAD

**Issue by minanagehsalalma** [OpenByteDev/EZBlocker3#4]
i opened the app in between songs an a video ad poped up and when i opened EZ to see if it works or not ... it showed playing advisement ... without muting or anything.

**Comment by OpenByteDev** [comment]
With the way EZBlocker3 currently works it is not possible to detect video ads. It would be possible to detect and block them by injecting custom javascript into the spotify app, but because for some reason I dont really have any video ads show up, its rather difficult to test any such blocking mechanism.

You should have a look at my new app [BurntSushi](https://github.com/OpenByteDev/BurntSushi) which is also a spotify ad blocker that uses an entirely different approach, which has no issues detecting ads and can actually block them (not just mute). It is currently in an early development stage and will get a better interface and settings.

**Comment by minanagehsalalma** [comment]
> it is not possible to detect video ads

no it's. as i said 

> and when i opened EZ to see if it works or not ... it showed playing advisement

if it was able to detect that's an ad was playing why wouldn't it just mute it ?

i mean a simple regex with keyword ad will do.

**Comment by OpenByteDev** [comment]
I'm sorry I assumed that it was not detected because generally they are not detected.
As for why it was not muted, I'm not sure - maybe video ads are played differently so it has do be done differently?

To debug this I would need you to enable "Debug Mode" in the settings, which will create a log.txt file next to the executable.

**Comment by minanagehsalalma** [comment]
> With the way EZBlocker3 currently works it is not possible to detect video ads. It would be possible to detect and block them by injecting custom javascript into the spotify app, but because for some reason I dont really have any video ads show up, its rather difficult to test any such blocking mechanism.
> 
> You should have a look at my new app [BurntSushi](https://github.com/OpenByteDev/BurntSushi) which is also a spotify ad blocker that uses an entirely different approach, which has no issues detecting ads and can actually block them (not just mute). It is currently in an early development stage and will get a better interface and settings.

Tested it , works perfectly.

but will crash if you opened it before opening Spotify.

**Comment by minanagehsalalma** [comment]
> To debug this I would need you to enable "Debug Mode" in the settings, which will create a log.txt file next to the executable.

well i will see if i get any and will report it back to u.

**Comment by OpenByteDev** [comment]
> but will crush if you opened it before opening Spotify.

BurntSushi currently has logging enabled by default. There should be a `log.txt` in `%localappdata%\OpenByte\BurntSushi`, would it be possible to send it to me or paste it here?

**Comment by minanagehsalalma** [comment]
> BurntSushi currently has logging enabled by default. There should be a `log.txt` in `%localappdata%\OpenByte\BurntSushi`, would it be possible to send it to me or paste it here?

looks like it replaces the log file with each restart ... i can't find the one with crash log. nor can reproduce it again.

also why the power usage is super high like that ? 
![image](https://user-images.githubusercontent.com/20546638/109676541-79d60980-7b81-11eb-9e8f-705135783193.png)

**Comment by OpenByteDev** [comment]
> looks like it replaces the log file with each restart ... i can't find the one with crash log. nor can reproduce it again.

I will look into that.

> also why the power usage is super high like that ?
> ![image](https://user-images.githubusercontent.com/20546638/109676541-79d60980-7b81-11eb-9e8f-705135783193.png)

I already fixed this, I will release a new version shortly. (The high CPU usage of spotify is related)

**Comment by minanagehsalalma** [comment]
> I already fixed this, I will release a new version shortly.

great , i will be waiting.

**Comment by OpenByteDev** [comment]
Here it is: https://github.com/OpenByteDev/BurntSushi/releases/tag/0.1.1

**Comment by minanagehsalalma** [comment]
@OpenByteDev 

here it's ... btw you know that mostly spotify takes time to open , right ?
```
[00:20:14 INF] Starting up...
[08:20:18 INF] Started Spotify Listener
[08:21:04 INF] Spotify hooked
[08:21:04 INF] Attempting to inject into process 4444
[08:21:26 ERR] Unhandled exception
System.ApplicationException: Unable to wait for service application due to timeout.
   at EasyHook.WOW64Bypass.Install()
   at EasyHook.RemoteHooking.InjectEx(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, String InLibraryPath_x86, String InLibraryPath_x64, Boolean InCanBypassWOW64, Boolean InCanCreateService, Boolean InRequireStrongName, Object[] InPassThruArgs)
   at BurntSushi.BurntSushi.Inject(Process process)
   at BurntSushi.Program.Inject(Process process)
   at BurntSushi.SpotifyProcessListener.OnSpotifyHooked(Process mainProcess, IntPtr mainWindowHandle)
   at BurntSushi.SpotifyProcessListener.HandleWindowCreation(IntPtr windowHandle)
   at WinEventHook.ReentrancySafeEventProcessor`1.ProcessQueue()
   at WinEventHook.WindowEventHook.OnWinEventProc(IntPtr hWinEventHook, WindowEvent eventType, IntPtr hwnd, AccessibleObjectID idObject, Int32 idChild, UInt32 dwEventThread, UInt32 dwmsEventTime)

```

**Comment by OpenByteDev** [comment]
I'm gonna add a retry mechanism on timeout

**Comment by OpenByteDev** [comment]
Please open any new issues with BurntSushi in the other repository in the future.

**Comment by minanagehsalalma** [comment]
Ok

**Comment by QGB** [comment]
编译生成都没问题，但是调试时候会出现错误：System.ApplicationException:Unable to wait for service application due to timeout
