### ISSUE TITLE
Not starting with spotify

### ISSUE THREAD

**Issue by ghost** [OpenByteDev/EZBlocker3#5]
When I am running spotify , EZBLOCKER is not running when I am executing spotify. Please Help !!!! Other features like run on startup are working pretty well but run with spotify function is not working . Another feature like check for updates is not working in my computer Please Help !!!!

**Comment by OpenByteDev** [comment]
Due to the way "Start with Spotify" is implemented it is error-prown. 
Can you try to disable it - Save the changes - Renenable it.
If this does not help have a look into the Spotify application folder and delete the `Spotify.proxy.exe` if present. You may also need to rename the `Spotify.real.exe` to `Spotify.exe` if present.

**Comment by ghost** [comment]
Ok But it is a bug ? And I am seeing Another bug where Spotify is getting muted on startup . Can u please help me with that ?                              - Thanks : )

**Comment by OpenByteDev** [comment]
It seems like a bug. Does it occur persistantly?

**Comment by ghost** [comment]
Ya Always when I try to start spotify

**Comment by OpenByteDev** [comment]
> If this does not help have a look into the Spotify application folder and delete the `Spotify.proxy.exe` if present. You may also need to rename the `Spotify.real.exe` to `Spotify.exe` if present.

Did you try this? What files were present?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/69617708/111747953-f07b4280-88b5-11eb-956a-40187dda62c7.png)
I already did it but still same not working .

**Comment by ghost** [comment]
Actually after enabling the Spotify works well But when I restart my pc and try to run Spotify it doesn't work. I mean the EZBLOCKER doesn't launch with Spotify.

**Comment by OpenByteDev** [comment]
Can you tell me the path the `Spotify.exe` is located in?

**Comment by ghost** [comment]
Ok it is working thanks a lot !!!! :)
