### ISSUE TITLE
EZBlocker is blocking music because it thinks it is a ad

### ISSUE THREAD

**Issue by ghost** [OpenByteDev/EZBlocker3#6]
So Today I was listening to some anime songs and I found that EZ Blocker is blocking this music 
https://open.spotify.com/episode/4BByGieLcZwMZZKocASgbU?si=lWaQMkFaRHGlXk7eQ5dS4w

It is a song and not a advertisement . 
Please Help me with this .

    - Thanks !!!!

**Comment by ghost** [comment]
I am using Burnt Sushi (https://github.com/OpenByteDev/BurntSushi) and it works perfectly well there !!!! Please help .

**Comment by OpenByteDev** [comment]
Can you enable the debug mode in the app settings, this will create a `log.txt` next to `EZBlocker3.exe`.
After encountering the issue again please send me the file or post it here (the last lines should suffice).

**Comment by ghost** [comment]
Debug mode is already enabled by default . I left the setting as it is .

**Comment by ghost** [comment]
Actually, when I am turning on aggressive muting it is muting the music and when I am turning it off the song is playing well.

**Comment by OpenByteDev** [comment]
> Debug mode is already enabled by default . I left the setting as it is .

That should not be the case:
Is there an orange border around the EZBlocker3 window?

**Comment by OpenByteDev** [comment]
> Actually, when I am turning on aggressive muting it is muting the music and when I am turning it off the song is playing well.

It's rather difficult to determine the error without the log.

**Comment by prorounak2005** [comment]
Can I enable both the ad blockers Burnt Sushi and EZBlocker ?

**Comment by prorounak2005** [comment]
![image](https://user-images.githubusercontent.com/69617708/111901179-602b3200-8a5c-11eb-8cb3-5d13e1d24bba.png)
I have enabled it.

**Comment by ghost** [comment]
Oh thanks a lot !!!! It really helped me . Can I close the issue ?
