### ISSUE TITLE
Regarding Video ads

### ISSUE THREAD

**Issue by ghost** [OpenByteDev/EZBlocker3#9]
I opened a new issue because of the video ads in Spotify and it is very annoying. Is there a way to remove it ? Can you do something about the video ads ? So that EZBlocker can easily remove those .

**Comment by OpenByteDev** [comment]
With the way EZBlocker3 currently works, I cannot remove the video ads.
This is why I decided to try an alternative blocking approach which is implemented in [BurntSushi](https://github.com/OpenByteDev/BurntSushi).
